### ISSUE TITLE
valueError

### ISSUE THREAD

**Issue by YashViradiya** [ChinHuan/finger-detection#1]
When b is pressed,it is closing camera window and giving an error:
 File "FingersNumberDetector.py", line 191, in detectHand
    _, contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)
Can you please help me?

**Comment by chinhuan** [comment]
I think this is just a version issue. Notice that the scripts are developed using OpenCV 3.2.0. Either you could install OpenCV 3.2.0 or change the code to unpack only two values.

```
contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
```

However, I cannot guarantee that there isn't any issue with the latter option.

**Comment by YashViradiya** [comment]
Tanks for the suggestion.. latter option is not giving any error..but my query is when I pressed b there is some small screen opening...and when i change fingers it doesn't show how many finger are there in screen...I mean the model is not predicting output. So, what to do next??
